<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.1</TargetFramework>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Compute.Bindings.IntelMKL" Version="0.1.5" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\MGroup.LinearAlgebra\MGroup.LinearAlgebra.csproj" />
  </ItemGroup>
  
  <ItemGroup>
	<InternalsVisibleTo Include="MGroup.LinearAlgebra.Tests" />
  </ItemGroup>

  <ItemGroup>
    <ContentWithTargetPath Include="lib\libamd.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <TargetPath>libamd.dll</TargetPath>
    </ContentWithTargetPath>
    <ContentWithTargetPath Include="lib\libbtf.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <TargetPath>libbtf.dll</TargetPath>
    </ContentWithTargetPath>
    <ContentWithTargetPath Include="lib\libcamd.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <TargetPath>libcamd.dll</TargetPath>
    </ContentWithTargetPath>
    <ContentWithTargetPath Include="lib\libccolamd.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <TargetPath>libccolamd.dll</TargetPath>
    </ContentWithTargetPath>
    <ContentWithTargetPath Include="lib\libcholmod.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <TargetPath>libcholmod.dll</TargetPath>
    </ContentWithTargetPath>
    <ContentWithTargetPath Include="lib\libcolamd.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <TargetPath>libcolamd.dll</TargetPath>
    </ContentWithTargetPath>
    <ContentWithTargetPath Include="lib\libcxsparse.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <TargetPath>libcxsparse.dll</TargetPath>
    </ContentWithTargetPath>
    <ContentWithTargetPath Include="lib\libklu.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <TargetPath>libklu.dll</TargetPath>
    </ContentWithTargetPath>
    <ContentWithTargetPath Include="lib\libldl.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <TargetPath>libldl.dll</TargetPath>
    </ContentWithTargetPath>
    <ContentWithTargetPath Include="lib\libspqr.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <TargetPath>libspqr.dll</TargetPath>
    </ContentWithTargetPath>
    <ContentWithTargetPath Include="lib\libumfpack.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <TargetPath>libumfpack.dll</TargetPath>
    </ContentWithTargetPath>
    <ContentWithTargetPath Include="lib\suitesparse_utilities.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <TargetPath>suitesparse_utilities.dll</TargetPath>
    </ContentWithTargetPath>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Update="Microsoft.CodeAnalysis.FxCopAnalyzers" Version="3.3.2">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers</IncludeAssets>
    </PackageReference>
  </ItemGroup>
</Project>
